version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: store
    ports:
      - 5432:5432
    restart: always

  store:
    build:
      context: .
      dockerfile: store/Dockerfile
    links:
      - auth
      - db
    ports:
      - 8088:8088
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
      BIND_ADDR: "0.0.0.0:8088"
    command: bash -c "./tools/wait.sh db:5432 -- ./hw1"
    depends_on:
      - db
      - auth
  
  auth:
    build:
      context: .
      dockerfile: auth/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:password@db/postgres
    ports:
      - 8089:8089
    depends_on:
      - db