version: "3"

services:
  app:
    build: .
    ports:
      - 8088:8088
    restart: always
    #command: ["./tools/wait.sh", "db:5432", "--", "./hw1"]
    links:
      - db
    networks:
      - net

  db:
    image: postgres
    ports:
      - 5432:5432
    #volumes:
    #  - ./db:/var/lib/postgresql/data
    environment:
      #-POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      #-PGDATA: /var/lib/postgresql/data
    restart: always
    networks:
      - net

networks:
  net: